version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - postgres-network
      - mongodb-network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: R9eAj4UH7meD8Typ
      POSTGRES_USER: bw_admin
      POSTGRES_DB: browser_workspace
    networks:
      - postgres-network

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bw_admin
      MONGO_INITDB_ROOT_PASSWORD: 7DKCKwpfTiY54xqk
      MONGO_INITDB_DATABASE: bw-images
    networks:
      - mongodb-network

volumes:
  postgres-data:
  mongodb-data:

networks:
  postgres-network:
  mongodb-network:
